env:
  TERM: alacritty

window:
  padding:
    x: 2
    y: 1

  dynamic_padding: true
  opacity: 1.0

font:
  normal:
    family: Sauce Code Pro Nerd Font Mono
    style: Regular
  bold:
    family: Sauce Code Pro Nerd Font Mono 
    style: Bold
  italic:
    family: Sauce Code Pro Nerd Font Mono
    style: Italic
  bold_italic:
    family: Sauce Code Pro Nerd Font Mono
    style: Bold Italic

  size: 8.0

  glyph_offset:
    x: 0
    y: 0

# Colors (Substrata)
colors:
  # Default colors
  primary:
    background: '#191c25'
    foreground: '#b5b4c9'

  # Cursor colors
  cursor:
    text: '#191c25'
    cursor: '#b5b4c9'

  # Normal colors
  normal:
    black:   '#191c25'
    red:     '#cf8164'
    green:   '#76a065'
    yellow:  '#ab924c'
    blue:    '#8296b0'
    magenta: '#a18daf'
    cyan:    '#659ea2'
    white:   '#b5b4c9'

  # Bright colors
  bright:
    black:   '#5b5f71'
    red:     '#fe9f7c'
    green:   '#92c47e'
    yellow:  '#d2b45f'
    blue:    '#a0b9d8'
    magenta: '#c6aed7'
    cyan:    '#7dc2c7'
 
