import = ["~/.config/alacritty/theme.toml"]

[font]
size = 8.0

[font.bold]
family = "SauceCodePro NFM"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro NFM"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro NFM"
style = "Italic"

[font.normal]
family = "SauceCodePro NFM"
style = "Regular"
