autoload -U colors && colors
PROMPT=$'%F{242}%~%f\n%B %b'
stty stop undef
HISTFILE=~/.cache/histfile
HISTSIZE=1000
SAVEHIST=5000
setopt autocd extendedglob
unsetopt beep
bindkey -v

autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)

# Custom scripts
source ~/.config/zsh/scripts/lfcd.sh
bindkey -s '^o' 'lfcd\n'

# Aliases
source ~/.config/zsh/alias

#Auto Suggestion
source ~/.config/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# Syntax highlighting
source ~/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
