if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

HISTFILE=~/.cache/histfile
HISTSIZE=1000
SAVEHIST=5000
setopt HIST_IGNORE_DUPS
setopt autocd extendedglob
unsetopt beep
bindkey -v

autoload -U compinit
zstyle ':completion:*' menu select matcher-list 'm:{a-z}={A-Z}'
zmodload zsh/complist
compinit
_comp_options+=(globdots)

source ~/.config/zsh/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh

# Custom scripts
source ~/.config/zsh/scripts

# Open lf and cd to the folder at exit
bindkey -s '^o' 'lfcd\n'
# Add other fzf goodness
export FZF_COMPLETION_TRIGGER='~~'
export FZF_ALT_C_COMMAND='find . -type d'

source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

# Exit on Ctrl-D even when there is text in prompt
exit_zsh() { exit }
zle -N exit_zsh
bindkey '^D' exit_zsh

# Aliases
source ~/.config/zsh/alias

#Auto Suggestion
source ~/.config/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# Syntax highlighting
source ~/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
